move function to .bashrc

diff --git a/ftnt-tools/code b/ftnt-tools/code
--- a/ftnt-tools/code
+++ b/ftnt-tools/code
@@ -1,75 +1,95 @@
 #!/bin/bash
 # set -x
 
-fNumOfCodePaths=
-fCodePaths=
+fForceSearch=
+fDebug=
+fArgs=("--goto")
+SCRIPTNAME=$(basename $0)
 MAGENTA='\033[0;35m'
 RESET='\033[0m'
 
-searchAndParse() {
-    local paths
-    findCmd="find $HOME/.vscode-server/cli -type f -name code -executable"
-    paths=$($findCmd)
-    if [[ -z $paths ]]; then
-        echo -e "${MAGENTA}Error: No code binary found in $HOME/.vscode-server/cli${RESET}"
-        exit 1
-    fi
-    # Originally, codePaths contains only one element joined by \n;
-    # It needs to be split into two separate elements.
-    # /home/userid/.vscode-server/bin/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/bin/remote-cli/code
-    # /home/userid/.vscode-server/bin/b1c0a14de1414fcdaa400695b4db1c0799bc3124/bin/remote-cli/code
-    IFS=$'\n' read -d '' -r -a fCodePaths <<< "$paths"
-    fNumOfCodePaths=${#fCodePaths[@]}
-    for i in "${!fCodePaths[@]}"
-    do
-        version=$(${fCodePaths[$i]} --version | head -n 1 | awk '{print $1}')
-        versionMap[$i]=$version
-    done
-}
+usage() {
+    cat << EOF
+Usage: $SCRIPTNAME [options] <args>
 
-printPathInfo () {
-    for i in "${!fCodePaths[@]}"
-    do
-        echo "${versionMap[$i]} : ${fCodePaths[$i]}"
-    done
-}
-
-function fcode() {
+Description:
+    A wrapper script for the VS Code server CLI.
+    It finds the VS Code server CLI binary and set the correct IPC socket.
+    The reason for this script is to avoid the bug which has never been fixed by Microsoft:
     # Unable to connect to VS Code server: Error in request - ENOENT /run/user/1000/vscode-ipc-*.sock
-    # https://github.com/microsoft/vscode-remote-release/issues/6997#issue-1319650016
-    # https://github.com/microsoft/vscode-remote-release/issues/6362#issuecomment-1046458477
+    https://github.com/microsoft/vscode-remote-release/issues/6997#issue-1319650016
+    https://github.com/microsoft/vscode-remote-release/issues/6362#issuecomment-1046458477
 
-    if [[ $fNumOfCodePaths -eq 0 ]]
-    then
-        echo "Error: No vscode code command found"
-        exit 1
-    elif [[ $fNumOfCodePaths -gt 1 ]]
-    then
-        echo -e "${MAGENTA}Error: More than one vscode code command found, please delete the older version(s) and try again.${RESET}"
-        printPathInfo
-        exit 1
-    fi
+Options:
+    -h, --help      Show this help message and exit
+    -f, --force     Force search for the code binary, ignoring \$VSCODE_BIN_PATH
+    -d, --debug     Enable debug mode (set -x)
 
-    local code syspath
-    code=${fCodePaths[0]}
-    syspath="/run/user/$UID"
-    # Get the latest vscode-ipc-*.sock file
-    new_IPC_HOOK=$(ls -t ${syspath}/vscode-ipc-*.sock | head -1)
-    if [[ -z $new_IPC_HOOK ]]
-    then
-        echo "Error: vscode-ipc-*.sock file not found";
-        exit 1
-    fi
+Example: $SCRIPTNAME --force
+         $SCRIPTNAME -d
+         $SCRIPTNAME -h
 
-    # Remove vscode-ipc-*.sock files except the latest one
-    # Cos a new vscode-ipc-*.sock file is created every time the vscode window is relaunched
-    find /run/user/$UID -maxdepth 1 -type s -name "vscode-ipc-*" ! -wholename "$new_IPC_HOOK" -delete
-
-    # VSCODE_IPC_HOOK_CLI is an environment variable that is used by the VS Code CLI to communicate with the server.
-    export VSCODE_IPC_HOOK_CLI=$new_IPC_HOOK
-
-    $code "$@"
+EOF
+    exit 0
 }
 
-searchAndParse
-fcode -g "$@"
+parseOptions() {
+    SHORTOPTS="hfdv"
+    LONGOPTS="help,force,debug,version"
+    if ! PARSED=$(getopt --options $SHORTOPTS --longoptions "$LONGOPTS" --name "$0" -- "$@"); then
+        echo -e "${MAGENTA}Error: Failed to parse command-line options.${RESET}" >&2
+        exit 1
+    fi
+    eval set -- "$PARSED"
+    while true; do
+        case "$1" in
+            -h|--help)
+                usage
+                ;;
+            -d|--debug)
+                fDebug=true
+                shift
+                ;;
+            -f|--force)
+                fForceSearch=true
+                shift
+                ;;
+            -v|--version)
+                fArgs+=("--version")
+                shift
+                ;;
+            --)
+                shift
+                break
+                ;;
+            *)
+                echo -e "${MAGENTA}Invalid option: $1${RESET}" >&2
+                exit 1
+        esac
+    done
+    [ -n "$1" ] && fArgs+=("$1")
+}
+
+preCheck() {
+    if ! declare -F setCodePath > /dev/null; then
+        echo -e "${MAGENTA}Error: setCodePath function is not defined.${RESET}" >&2
+        exit 1
+    fi
+}
+
+main() {
+    preCheck
+    parseOptions "$@"
+    [ -n "$fDebug" ] && set -x
+    [ -z "$VSCODE_BIN_PATH" ] || [ -n "$fForceSearch" ] && setCodePath
+    for _ in {1..2}; do
+        "$VSCODE_BIN_PATH" "${fArgs[@]}"
+        if [[ $? -eq 0 ]]; then
+            break
+        else
+            setCodePath
+        fi
+    done
+}
+
+main "$@"
diff --git a/track-files/bashrc b/track-files/bashrc
--- a/track-files/bashrc
+++ b/track-files/bashrc
@@ -92,15 +92,58 @@ alias cdN='__cd /usr/local/nginx'
 export QUOTING_STYLE=literal
 # set theme for the bat(batcat) command
 export BAT_THEME=TwoDark
+# VSCode settings
+setCodePath() {
+    [ -z "$VSCODE_IPC_HOOK_CLI" ] && return
+    local paths searchDir count version syspath newIPCHooK
+    local -A map=()
+    local MAGENTA='\033[0;35m'
+    local LIGHTYELLOW='\033[93m'
+    local RESET='\033[0m'
+    syspath="/run/user/$UID"
+    searchDir="$HOME/.vscode-server/cli"
+
+    readarray -d '' paths < <(find "$searchDir" -type f -name code -executable -print0)
+    count=${#paths[@]}
+    if [[ $count -eq 0 ]]; then
+        echo -e "${MAGENTA}Error: No code binary found under $searchDir${RESET}" >&2
+    elif [[ $count -gt 1 ]]; then
+        echo -e "${LIGHTYELLOW}Error: Please remove the older versions of code.${RESET}" >&2
+        for path in "${paths[@]}"
+        do
+            version=$("$path" --version | head -n 1 | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
+            map["$path"]=$version
+        done
+        for path in "${!map[@]}"
+        do
+            echo -e "${MAGENTA}${map[$path]}${RESET} : $path"
+        done
+    fi
+
+    # Get the most recenely created/modified vscode-ipc-*.sock file
+    newIPCHooK=$(find "$syspath" -maxdepth 1 -type s -name 'vscode-ipc-*.sock' -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n 1 | cut -d' ' -f2-)
+    if [[ -z $newIPCHooK ]]
+    then
+        echo -e "${MAGENTA}Error: No vscode-ipc-*.sock file found in $syspath${RESET}" >&2
+    fi
+
+    # Remove unused vscode-ipc-*.sock files
+    find "$syspath" -maxdepth 1 -type s -name "vscode-ipc-*.sock" ! -wholename "$newIPCHooK" -delete
+
+    # VSCODE_IPC_HOOK_CLI is an environment variable that is used by the VS Code CLI to communicate with the server.
+    # But you have to remember that only the sub shell can see the new value.
+    export VSCODE_IPC_HOOK_CLI=$newIPCHooK
+    export VSCODE_BIN_PATH="${paths[0]}"
+}
+export -f setCodePath
 
 # Useful local variables.
 export LC_ALL=en_US.UTF-8
 export LANG=en_US.UTF-8
 export LC_CTYPE=en_US.UTF-8
 # export SHELL=/bin/bash
-export EDITOR=vim
-# Wireshark to decode SSL/TLS traffic
-export SSLKEYLOGFILE=~/.ssl-keys.log
+# export EDITOR=vim
+export SSLKEYLOGFILE=~/.ssl-keys.log # Wireshark to decode SSL/TLS traffic
 PKG_CONFIG_PATH=$HOME/.usr/lib/pkgconfig:/usr/local/lib/pkgconfig
 LD_LIBRARY_PATH=/usr/lib:/usr/lib64:/usr/local/lib:/usr/local/lib64
 LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.usr/lib:$HOME/.usr/lib64
@@ -112,18 +155,10 @@ export PATH
 export PKG_CONFIG_PATH
 export LD_LIBRARY_PATH
 unset TMOUT
-# FOS variables.
-export FORTIPKG="$HOME/fortipkg"
-# export USESUDO=`which sudo`
-# alias build_tags='ctags -R --extra=+f --languages=C,+C++ --links=no;cscope -Rbqk'
-
-# Enable programmable completion features (you don't need to enable
-# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
-# sources /etc/bash.bashrc).
+export FORTIPKG="$HOME/fortipkg" # FOS variables.
 if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
     . /etc/bash_completion
 fi
-
 # find bash completion for third-party tools | only for Mac
 if [[ -d /usr/local/etc/bash_completion.d ]]; then
     for file in /usr/local/etc/bash_completion.d/*; do
@@ -131,10 +166,9 @@ if [[ -d /usr/local/etc/bash_completion.d ]]; then
         [[ -L $file ]] && . "$file"
     done
 fi
-
-extraCompletionDir="$HOME/.bash_completion.d"
-if [[ -d "$extraCompletionDir" ]]; then
-    for file in "$extraCompletionDir"/*; do
+trackedCompletionDir="$HOME/.bash_completion.d"
+if [[ -d "$trackedCompletionDir" ]]; then
+    for file in "$trackedCompletionDir"/*; do
         # shellcheck disable=SC1090
         [[ -f $file ]] && source "$file"
     done
@@ -195,3 +229,4 @@ export FZF_COMPLETION_OPTS='+c -x'
 # For fzf-tab-completion vim plugin
 bind -r "*\t"
 bind -x '"*\t": fzf_bash_completion'
+setCodePath
