update jr to support more random input

diff --git a/ftnt-tools/code b/ftnt-tools/code
--- a/ftnt-tools/code
+++ b/ftnt-tools/code
@@ -7,6 +7,11 @@ function fcode() {
 
     findCmd="find $HOME/.vscode-server/bin -type f -name code -executable"
     codePaths=$($findCmd)
+    if [[ -z $codePaths ]]
+    then
+        echo "Error: vscode code command not found";
+        exit 1
+    fi
 
     splitPaths() {
         # Originally, codePaths contains only one element joined by \n; it needs to be split into two separate elements.
@@ -28,12 +33,6 @@ function fcode() {
         done
     }
 
-    if [[ -z ${codePaths[0]} ]]
-    then
-        echo "Error: vscode code command not found";
-        exit 1
-    fi
-
     splitPaths
 
     if [[ ${#codePaths[@]} -gt 1 ]]
@@ -45,7 +44,7 @@ function fcode() {
 
     codePath=${codePaths[0]}
     sysPath="/run/user/$UID"
-    # List all the vscode-ipc-*.sock files and get the latest one
+    # Get the latest vscode-ipc-*.sock file
     new_IPC_HOOK=$(ls -t ${sysPath}/vscode-ipc-*.sock | head -1)
     if [[ -z $new_IPC_HOOK ]]
     then
@@ -61,7 +60,8 @@ function fcode() {
 
     # VSCODE_IPC_HOOK_CLI is an environment variable that is used by the VS Code CLI to communicate with the server.
     export VSCODE_IPC_HOOK_CLI=$new_IPC_HOOK
-    $codePath $@
+    # echo the passed arguments
+    $codePath "$@"
 }
 
-fcode -g $@
+fcode -g "$@"
diff --git a/ftnt-tools/jr b/ftnt-tools/jr
--- a/ftnt-tools/jr
+++ b/ftnt-tools/jr
@@ -1,11 +1,15 @@
 #!/bin/bash
+# set -x
 
 scriptName=$(basename $0)
-fUseVim=false
-EDITOR="code"
-
-# The user notation
 USER_NOTATION="@@@@"
+EDITOR="code"
+# Colors
+MAGENTA='\033[35m'
+NORMAL='\033[0m'
+BOLD='\033[1m'
+RESET='\033[0m'
+COLOR=$MAGENTA
 
 usage() {
     cat << _EOF_
@@ -14,7 +18,7 @@ $scriptName v0.0
 Usage: $scriptName [vz] <search term>
 
 Options:
-    -v  Open the file in vim (default is $EDITOR)
+    -v  Open the file with vim (default is $EDITOR)
     -z  Search with empty query
 
 Example: $scriptName "search term"
@@ -34,7 +38,7 @@ query="$@"
 while getopts "hvz" opt; do
     case ${opt} in
         v)
-            fUseVim=true
+            EDITOR="vim"
             ;;
         z)
             query=""
@@ -70,43 +74,81 @@ preCheck() {
         echo "$USER_NOTATION bat is not installed"
         exit 1
     fi
+
+    if ! command -v $EDITOR &> /dev/null; then
+        echo "$USER_NOTATION $EDITOR is not installed"
+        exit 1
+    fi
+}
+
+parserAndPolish() {
+    local param
+    # Remove the leading and trailing spaces
+    param=$(echo "$query" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
+
+    # Polish query like <wad_http_req_setup_casb>
+    pattern='^<(.*)>$'
+    if [[ $param =~ $pattern ]]; then
+        param="${BASH_REMATCH[1]}"
+    fi
+    # Polish query like wad_http_req_setup_casb:3071
+    pattern='^(.*)\:[0-9]+$'
+    if [[ "$param" =~ $pattern ]]; then
+        param="${BASH_REMATCH[1]}"
+    fi
+    query="$param"
 }
 
 preCheck
+parserAndPolish
 
-# wad_ssl_sock_port_exec_up_forward_txn:17850 => wad_ssl_sock_port_exec_up_forward_txn
-query_polished=$(echo "$query" | sed 's/\\//g' | cut -d: -f1)
+# result=$(rg --smart-case \
+#             --color=ansi \
+#             --colors 'match:fg:204,51,153' --colors 'match:style:bold' \
+#             --line-number --no-heading "$query" |
+#         fzf --ansi \
+#             --color 'hl:-1:underline,hl+:-1:underline:reverse' \
+#             --delimiter ':' \
+#             --preview "bat --color=always {1} --theme='TwoDark' --highlight-line {2}" \
+#             --preview-window 'top,60%,border-bottom,+{2}+3/3,~3' \
+#             --cycle \
+#             --query "$query")
 
-# write the three check into a function
-result=$(rg --smart-case \
+rgResult=$(rg --smart-case \
             --color=ansi \
             --colors 'match:fg:204,51,153' --colors 'match:style:bold' \
-            --line-number --no-heading "$query_polished" |
+            --line-number --no-heading "$query")
+if [ -z "$rgResult" ]; then
+    echo -e "${COLOR}No result found${RESET}"
+    exit 1
+fi
+
+fzfResult=$(echo "$rgResult" |
         fzf --ansi \
             --color 'hl:-1:underline,hl+:-1:underline:reverse' \
             --delimiter ':' \
             --preview "bat --color=always {1} --theme='TwoDark' --highlight-line {2}" \
             --preview-window 'top,60%,border-bottom,+{2}+3/3,~3' \
             --cycle \
-            --query "$query_polished")
+            --query "$query")
+if [ -z "$fzfResult" ]; then
+    exit 0
+fi
 
-# The sample value of result is:
+# Sample output of fzfResult:
 # daemon/wad/wad_app_eng.c:3071:          goto session_make_failed;
-if [ -z "$result" ]; then
-    exit 0
-fi
-
-file="${result%%:*}"
-linenumber=$(echo "${result}" | cut -d: -f2)
-
-if [ "$fUseVim" = true ]; then
-    EDITOR="vim"
-    $EDITOR +"${linenumber}" "$file"
-    exit 0
-fi
-
-if ! command -v $EDITOR &> /dev/null; then
-    echo "$USER_NOTATION $EDITOR is not installed"
+pattern='([a-zA-Z0-9/.%_-]+):([0-9]+)'
+if [[ $fzfResult =~ $pattern ]]; then
+    file="${BASH_REMATCH[1]}"
+    linenumber="${BASH_REMATCH[2]}"
+else
+    echo -e "${COLOR}Error: The result is in unexpected format${RESET}"
     exit 1
 fi
-$EDITOR "$file":"$linenumber"
+
+if [ "$EDITOR" == "vim" ]; then
+    $EDITOR +"${linenumber}" "$file"
+    exit 0
+else
+    $EDITOR "$file":"$linenumber"
+fi
