update jindex

diff --git a/ftnt-tools/jindex b/ftnt-tools/jindex
--- a/ftnt-tools/jindex
+++ b/ftnt-tools/jindex
@@ -1,5 +1,26 @@
 #!/bin/bash
 
+usage() {
+cat << _EOF
+Usage: jindex [-h]
+Update all Git repositories in the /opt/src directory and call the indexer.
+
+_EOF
+    exit 1
+}
+
+while getopts ":h" opt; do
+    case ${opt} in
+        h)
+           usage
+           ;;
+        ?)
+            echo "Invalid option: $OPTARG" 1>&2
+            exit 1
+            ;;
+    esac
+done
+
 if ! command -v get_credentials &> /dev/null; then
     echo "Error: Command get_credentials not found."
     exit 1
