add promption

diff --git a/ftnt-tools/jr b/ftnt-tools/jr
--- a/ftnt-tools/jr
+++ b/ftnt-tools/jr
@@ -147,6 +147,11 @@ checkDepends() {
 GetClipboardContent() {
     if [ -z "$fQuery" ] && [ -n "$DISPLAY" ]; then
         fQuery=$(xsel -o -p 2> /dev/null)
+        if [[ $? -ne 0 ]]; then
+            echo -e "${COLOR}Error: Failed to get PRIMARY clipboard content${RESET}"
+            echo -e "${COLOR}Please check the status of the X server${RESET}"
+            exit 1
+        fi
         [ -n "$fQuery" ] && fQueryFromClipboard=true
     fi
 }
