remove a option of jmake

diff --git a/ftnt-tools/jssh b/ftnt-tools/jssh
--- a/ftnt-tools/jssh
+++ b/ftnt-tools/jssh
@@ -42,7 +42,7 @@ while getopts "p:u:h" opt; do
             usage
             ;;
         ?)
-            echo "$userNotation Invalid option: -$OPTARG" >&2
+            echo "$user_notation Invalid option: -$OPTARG" >&2
             exit 1
             ;;
     esac
@@ -62,7 +62,7 @@ expect -c "
 
     for {set i 1} {\$i <= $max_iterations} {incr i} {
         # ssh -o StrictHostKeyChecking=no $fgt_name
-        # send_user \"$subUserNotation Sync attempt \$i/$max_iterations\n\"
+        # send_user \"Sync attempt \$i/$max_iterations\n\"
         spawn -noecho ssh $login_user@$fgt_name
 
         expect {
