add -P prompt option for jssh

diff --git a/ftnt-tools/jssh b/ftnt-tools/jssh
--- a/ftnt-tools/jssh
+++ b/ftnt-tools/jssh
@@ -4,11 +4,13 @@ script_name=$(basename $0)
 user_notation="@@@@"
 password=""
 login_user="admin"
+fgt_prompt="# "
 fgt_name="fgt1"
 max_iterations=2
 
 usage() {
 cat << _EOF
+jssh 0.0
 
 usage:
     $script_name [-p password] [-u user] [-t fgt_name/fgt_ip]
@@ -16,6 +18,7 @@ usage:
 Options:
     -u user             User to use for login. Default is "$login_user"
     -p password         Password to use for login. Default is "$password"
+    -P prompt           Prompt to expect. Default is "$fgt_prompt"
     -t fgt_name/fgt_ip  The device to connect to. Default is "$fgt_name"
 
 Example:
@@ -30,7 +33,7 @@ _EOF
 [[ $# -eq 0 ]] && usage
 
 # Parse command-line options
-while getopts "p:u:t:h" opt; do
+while getopts "p:u:t:P:h" opt; do
     case ${opt} in
         p)
             password=$OPTARG
@@ -40,6 +43,9 @@ while getopts "p:u:t:h" opt; do
             ;;
         t)
             fgt_name=$OPTARG
+            ;;
+        P)
+            fgt_prompt=$OPTARG
             ;;
         h)
             usage
@@ -58,9 +64,8 @@ if [[ $# -gt 0 ]]; then
     exit
 fi
 
+# expect -d -c "
 expect -c "
-    set fgt_prompt \"# \"
-
     for {set i 1} {\$i <= $max_iterations} {incr i} {
         # ssh -o StrictHostKeyChecking=no $fgt_name
         # send_user \"Sync attempt \$i/$max_iterations\n\"
@@ -94,7 +99,7 @@ expect -c "
                 puts \"Timed out waiting for a response.\"
                 exit 1
             }
-            \$fgt_prompt {
+            \"$fgt_prompt\" {
                 puts \"$user_notation Successfully connected to $fgt_name\"
                 break
             }
@@ -102,7 +107,7 @@ expect -c "
     }
 
     send \"\r\"
-    expect \$fgt_prompt
+    expect \"$fgt_prompt\"
 
     # Now you can add additional commands or interactions as needed
     # For example, you can automate further commands here
@@ -110,3 +115,54 @@ expect -c "
     # Interact with the device
     interact
 "
+
+# + expect -d -c '
+#     for {set i 1} {$i <= 2} {incr i} {
+#         # ssh -o StrictHostKeyChecking=no 172.18.20.230
+#         # send_user "Sync attempt $i/2\n"
+#         spawn -noecho ssh admin@172.18.20.230
+
+#         expect {
+#             {yes/no} {
+#                 send "yes\r"
+#                 exp_continue
+#             }
+#             -re {[Pp]assword} {
+#                 send "\r"
+#                 exp_continue
+#             }
+#             "Host key verification failed." {
+#                 send_user "@@@@ Host key verification failed. Updating known_hosts file...\n"
+#                 system "ssh-keygen -R 172.18.20.230"
+#                 send_user "@@@@ Host key removed from known_hosts file.\n"
+#                 send_user "@@@@ Retrying SSH immediately...\n"
+#                 continue
+#             }
+#             "Connection refused" {
+#                 send_user "@@@@ Connection refused. Exiting...\n"
+#                 exit 1
+#             }
+#             eof {
+#                 puts "Reached EOF. Exiting..."
+#                 exit 1
+#             }
+#             timeout {
+#                 puts "Timed out waiting for a response."
+#                 exit 1
+#             }
+#             "# " {
+#                 puts "@@@@ Successfully connected to 172.18.20.230"
+#                 break
+#             }
+#         }
+#     }
+
+#     send "\r"
+#     expect "# "
+
+#     # Now you can add additional commands or interactions as needed
+#     # For example, you can automate further commands here
+
+#     # Interact with the device
+#     interact
+# '
