rewrite jupall

diff --git a/ftnt-tools/jupall b/ftnt-tools/jupall
--- a/ftnt-tools/jupall
+++ b/ftnt-tools/jupall
@@ -15,52 +15,44 @@ ftntUser=${credentials[0]}
 ftntPasswd=${credentials[1]}
 
 USER_NOTATION="@@@@"
-SCRIPT_LOCATION="/tmp/git_fetch_repos"
+SCRIPT_LOCATION="/tmp/git_upall_repos"
 
 # check if the script exists
-if [ ! -f "$SCRIPT_LOCATION" ]; then
+if [ -f "$SCRIPT_LOCATION" ]; then
     cat << _EOF > $SCRIPT_LOCATION
 #!/bin/bash
 # set -x
 
-repos=(
-    "/data/fos"
-    "/data/fos2"
-    "/data/fpx"
-    "/data/fpx2"
-    "/data/sandbox/fos_repro"
-    "/data/sandbox/fpx_repro"
-    "/data/sandbox/fortios-ci"
-)
+repo_dir="/opt/src"
 
 update_git_repo() {
     local repo_path="\$1"
+    echo -e "\n$USER_NOTATION Updating repository: \$repo_path"
 
-    echo -e  "\n$USER_NOTATION Updating repository: \$repo_path"
-
-    # Change to the repository directory
-    cd "\$repo_path" || exit 1
-
+    # switch to the repository directory
+    cd "\$repo_path" || return 1
     # Check if it's a Git repository
     if [ -d ".git" ]; then
+        # Get the current branch name
+        current_branch=$(git symbolic-ref --short HEAD 2>/dev/null)
+        # check the return code, if error then exit
+        if [ \$? -ne 0 ]; then
+            echo "$USER_NOTATION Warning: Not on any branch"
+            return 1
+        fi
+
+        # git pull current branch
         echo "$USER_NOTATION Fetching tags:"
         git fetch --tags
-        # Check if fetching was successful
-        if [ $? -ne 0 ]; then
-            echo "$USER_NOTATION Error fetching tags. Aborting."
+        if [ \$? -ne 0 ]; then
+            echo "@@@@ Error fetching tags. Aborting."
             exit 1
         fi
-        echo "$USER_NOTATION Fetching branches: main"
-        git fetch origin main
-        echo "$USER_NOTATION Fetching branches: 7.0"
-        git fetch origin 7.0
-        echo "$USER_NOTATION Fetching branches: 7.2"
-        git fetch origin 7.2
-        # FPX does not have 7.4 branch currently. Mar.11 2024
-        # git ls-remote --exit-code --quiet --heads origin 7.4
-        git ls-remote --exit-code --quiet --heads origin 7.4
-        if [ $? -eq 0 ]; then
-            git fetch origin 7.4
+        echo "$USER_NOTATION Pulling the current branch: \$current_branch"
+        git pull --rebase
+        if [ \$? -ne 0 ]; then
+            echo "$USER_NOTATION Error: Failed to pull the current branch: \$current_branch"
+            exit 1
         fi
     else
         echo "$USER_NOTATION Not a Git repository: \$repo_path"
@@ -70,14 +62,33 @@ update_git_repo() {
     cd - &>/dev/null
 }
 
-for repo in "\${repos[@]}"; do
+# Check if the directory exists
+if [ ! -d "\$repo_dir" ]; then
+    echo "$USER_NOTATION Error: The directory \$repo_dir does not exist."
+    exit 1
+fi
+
+# List all subdirectories in the repository directory
+# -o: logical OR operator. It allows to specify an alternative condition for the search.
+repos=\$(find "\$repo_dir" -mindepth 1 -maxdepth 1 -type d -o -type l | sort)
+
+# Loop through each repository and update it
+for repo in \$repos; do
     update_git_repo "\$repo"
 done
 
-if [ ! -x "$SCRIPT_LOCATION" ]; then
-    chmod +x $SCRIPT_LOCATION
+# call the indexer
+if command -v callIndexer &> /dev/null; then
+    # The command callIndexer exists, so you can execute it
+    callIndexer -u
+else
+    echo "$USER_NOTATION callIndexer command not found"
 fi
 _EOF
+    # check if the script executable
+    if [ ! -x "$SCRIPT_LOCATION" ]; then
+        chmod +x $SCRIPT_LOCATION
+    fi
 fi
 
 expect -c "
