add reinstall options

diff --git a/ftnt-tools/jvpn b/ftnt-tools/jvpn
--- a/ftnt-tools/jvpn
+++ b/ftnt-tools/jvpn
@@ -1,32 +1,66 @@
 #!/bin/bash
+# set -x
 
 # Set the header for the Expect script
 SCRIPT_NAME=$(basename $0)
 GET_COLORS="$HOME/Templates/getcolors.sh"
+fForticlientPkgPath="$HOME/Downloads/forticlient_7.2.0.0644_amd64.deb"
 
 if [ -f "$GET_COLORS" ]; then
     source "$GET_COLORS"
 fi
 
-
 usage() {
-    echo "Usage: $SCRIPT_NAME [-r]"
-    echo "  -r  Restart the forticlient service"
-    exit 1
+cat <<EOF
+Usage: $SCRIPT_NAME [-r]
+  -r  Restart the forticlient service
+  -R  Reinstall forticlient
+  -h  Display this help message
+
+EOF
+exit 1
 }
 
-while getopts "rh" opt; do
+reInstallForticlient() {
+    echo -e "${COLOR}Reinstalling forticlient${RESET}"
+    echo -e "${COLOR}Removing forticlient${RESET}"
+    sudo apt-get remove forticlient
+
+    echo -e "${COLOR}Installing forticlient${RESET}"
+    if [ ! -f "$fForticlientPkgPath" ]; then
+        echo -e "${COLOR}Forticlient path does not exist${RESET}"
+        exit 1
+    fi
+    forticlientDir=$(dirname "$fForticlientPkgPath")
+    cd "$forticlientDir" || exit 1
+    sudo dpkg -i "$fForticlientPkgPath"
+    if [ $? -ne 0 ]; then
+        echo -e "${COLOR}Failed to reinstall forticlient${RESET}"
+        exit 1
+    else
+        echo -e "${COLOR}Successfully installed forticlient${RESET}"
+    fi
+}
+
+restartForticlientService() {
+    echo -e "${COLOR}Restarting forticlient service${RESET}"
+    sudo systemctl restart forticlient.service
+    if [ $? -ne 0 ]; then
+        echo -e "${COLOR}Failed to restart forticlient service${RESET}"
+        exit 1
+    else
+        echo -e "${COLOR}Successfully restarted forticlient service${RESET}"
+        sudo systemctl status forticlient.service
+    fi
+}
+
+while getopts "rRh" opt; do
     case $opt in
         r)
-            echo -e "${COLOR}Restarting forticlient service${RESET}"
-            sudo systemctl restart forticlient.service
-            # sudo systemctl status forticlient.service
-            if [ $? -ne 0 ]; then
-                echo -e "${COLOR}Failed to restart forticlient service${RESET}"
-                exit 1
-            else
-                echo -e "${COLOR}Successfully restarted forticlient service${RESET}"
-            fi
+            restartForticlientService
+            ;;
+        R)
+            reInstallForticlient
             ;;
         h)
             usage
@@ -52,8 +86,9 @@ mapfile -t credentials <<< "$credentials_output"
 ftnt_username=${credentials[0]}
 ftnt_password=${credentials[1]}
 
+echo -e "${COLOR}Starting the VPN connection${RESET}"
 spawnCmd="sudo /opt/forticlient/vpn -s scm.van.corp.fortinet.com:443 -u $ftnt_username -p"
-echo "Spawned command: $spawnCmd"
+echo -e "${COLOR}Spawned command: $spawnCmd${RESET}"
 
 expect -c "
     set timeout 60
