add del vms

diff --git a/ftnt-tools/restore_vms b/ftnt-tools/restore_vms
--- a/ftnt-tools/restore_vms
+++ b/ftnt-tools/restore_vms
@@ -17,14 +17,45 @@ if [ ! -f "$backup_vm" ]; then
     exit 1
 fi
 
+# check if the VM is running
+sleep_time=5
+max_loop_cnt=2
+
+vm_status=$(virsh list --all | grep "$vm_name" | awk '{print $3}')
+if [ "$vm_status" == "running" ]; then
+    echo "VM $vm_name is running, shutdown it now."
+    virsh shutdown "$vm_name"
+
+    # wait for the VM to shutdown
+    sleep $sleep_time
+    loop_cnt=0
+    vm_status=$(virsh list --all | grep "$vm_name" | awk '{print $3}')
+    while [ "$vm_status" == "running" ]; do
+		if [[ $loop_cnt -ge $max_loop_cnt ]]; then
+            echo "Error: VM $vm_name is still running after $loop_cnt loops, exit."
+            exit 1
+        fi
+        echo "VM $vm_name is still running, sleep $sleep_time seconds and check again."
+        sleep $sleep_time
+        loop_cnt=$((loop_cnt+1))
+        vm_status=$(virsh list --all | grep "$vm_name" | awk '{print $3}')
+    done
+fi
+
+echo "Restore XML configuration file"
+sudo rsync -av "$backup_dir/$vm_name.xml" "/etc/libvirt/qemu/$vm_name.xml"
+
 echo "Restoring VM: $vm_name"
 sudo cp -v "$backup_vm" "$target_dir/$vm_name.qcow2"
 
 file_owner=$(stat -c %U "$target_dir/$vm_name.qcow2")
-if [ "$file_owner" == "libvirt-qemu" ]; then
-    exit 1
+if [ "$file_owner" != "libvirt-qemu" ]; then
+    echo "Change owner of $vm_name.qcow2 to libvirt-qemu:kvm"
+    sudo chown -v libvirt-qemu:kvm "$target_dir/$vm_name.qcow2"
 fi
 
-sudo chown -v libvirt-qemu:kvm "$target_dir/$vm_name.qcow2"
-
 echo "Restore complete for VM: $vm_name"
+echo "Restart libvirtd service if needed."
+echo "sudo systemctl restart libvirtd"
+
+# sudo systemctl restart libvirtd
