remove right shift

diff --git a/ftnt-tools/start_all_vms b/ftnt-tools/start_all_vms
--- a/ftnt-tools/start_all_vms
+++ b/ftnt-tools/start_all_vms
@@ -7,20 +7,19 @@ vm_list=$(sudo virsh list --all --name)
 for vm in $vm_list; do
     # fgt3: fips-cc special
     # fpx2: fips-cc special
-    if [[ "$vm" == "fgt3" || "$vm" == "fpx2" || "$vm" == "client1" || "$vm" == "client4" || "$vm" == "fpx3" ]]; then
-        continue
-    fi
-    # Check if the VM is running
-    if sudo virsh domstate "$vm" | grep -q "running"; then
-        echo "VM '$vm' is already running."
-        continue
-    fi
+    if [[ "$vm" == "client2" || "$vm" == "client3" || "$vm" == "fgt1" || "$vm" == "fpx1" ]]; then
+        # Check if the VM is running
+        if sudo virsh domstate "$vm" | grep -q "running"; then
+            echo "VM '$vm' is already running."
+            continue
+        fi
 
-    # Start the VM if it's not running
-    sudo virsh start "$vm"
-    if [ $? -ne 0 ]; then
-        echo "Failed to start VM: $vm"
-        echo "Use sudo lsof -i :[Port_Number] to check if the vnc port of $vm is in use."
-        echo "And then use kill <PID> to kill the process."
+        # Start the VM if it's not running
+        sudo virsh start "$vm"
+        if [ $? -ne 0 ]; then
+            echo "Failed to start VM: $vm"
+            echo "Use sudo lsof -i :[Port_Number] to check if the vnc port of $vm is in use."
+            echo "And then use kill <PID> to kill the process."
+        fi
     fi
 done
