add --no-clipboard options

diff --git a/recycled/jr b/recycled/jr
--- a/recycled/jr
+++ b/recycled/jr
@@ -6,7 +6,6 @@ fEditor="code"
 fDebug=
 fRgOnly=
 fCheckDepends=
-fNoClipboard=
 fzfSelected=
 fQuery=
 fKernelIncluded=  # Include the linux kernel source code in the search
@@ -54,10 +53,10 @@ _EOF
 parseOptions() {
     # Define short and long options
     SHORTOPTS="hvdrkc"
-    LONGOPTS="help,vim,debug,kernel,rg-only,check-depends, no-clipboard"
+    LONGOPTS="help,vim,debug,kernel,rg-only,check-depends"
 
     # Use getopt to parse command-line options
-    if ! PARSED=$(getopt --options $SHORTOPTS --longoptions "$LONGOPTS" --name "$0" -- "$@"); then
+    if ! PARSED=$(getopt --options $SHORTOPTS --longoptions $LONGOPTS --name "$0" -- "$@"); then
         echo -e "$USER_NOTATION ${COLOR}Error: Failed to parse command-line options.${RESET}" >&2
         exit 1
     fi
@@ -85,10 +84,6 @@ parseOptions() {
                 ;;
             -c|--check-depends)
                 fCheckDepends=true
-                shift
-                ;;
-            --no-clipboard)
-                fNoClipboard=true
                 shift
                 ;;
             -r|--rg-only)
@@ -195,24 +190,16 @@ fuzzySearch() {
     if [ -n "$fDebug" ]; then
         echo $SEPARATOR_RIGHT
         # ${array[*]} => Expands to a single string where all elements are joined together
-        # ${array[@]} => Expands to a list of individual elements
-        # TODO: Print the array with either echo or printf will remove all the original single quotes.
-        echo -e "rgQuery: ${COLOR}${rgParams[*]}${RESET}"
-        echo -e "fzfQuery: ${COLOR}${fzfParams[*]}${RESET}"
-    fi
-
-    if [ -n "$fRgOnly" ]; then
-        echo $SEPARATOR_LEFT
-        rg "${rgParams[@]}"
-        exit 0
+        echo -e "rgQuery: ${COLOR}rg ${rgParams[*]}${RESET}"
+        echo -e "fzfQuery: ${COLOR}fzf ${fzfParams[*]}${RESET}"
     fi
 
     # Unified search and selection
+    # ${array[@]} => Expands to a list of individual elements
     fzfSelected=$(rg "${rgParams[@]}" | fzf "${fzfParams[@]}")
 
     if [ -z "$fzfSelected" ]; then
-        [ -n "$fQuery" ] && echo -e "No result found or selected for query: ${COLOR}$fQuery${RESET}" >&2
-        [ -n "$fDebug" ] && echo $SEPARATOR_LEFT
+        echo -e "No result found or selected for query: ${COLOR}$fQuery${RESET}" >&2
         exit 0
     fi
 
@@ -247,10 +234,93 @@ fuzzySearch() {
     fi
 }
 
+# fuzzySearch() {
+#     # --glob='*.{c,h,cpp,js,ts,py,html,css,sh,php}'
+#     local kernelSearch="--glob='!linux-*/*'"
+#     local rgParams="--smart-case \
+#                     --color=ansi \
+#                     --colors 'match:fg:204,51,153' --colors 'match:style:bold' \
+#                     --line-number \
+#                     --no-heading \
+#                     --glob='!fpx-sync/*' \
+#                     --glob='!linux-3.2.16/*' \
+#                    "
+#     local fzfParams="--ansi \
+#                      --color 'hl:-1:underline,hl+:-1:underline:reverse' \
+#                      --delimiter ':' \
+#                      --preview 'bat --color=always {1} --theme=\"TwoDark\" --highlight-line {2}' \
+#                      --preview-window 'top,60%,border-bottom,+{2}+3/3,~3' \
+#                      --cycle \
+#                     "
+#     if [ -z "$fKernelIncluded" ]; then
+#         rgParams="$rgParams $kernelSearch"
+#     fi
+
+#     # Squash multiple whitespaces
+#     rgParams=$(echo "$rgParams" | tr -s ' ')
+#     fzfParams=$(echo "$fzfParams" | tr -s ' ')
+
+#     # Make the query command
+#     rgQuery="rg $rgParams \"$fQuery\""
+#     # Remove the backslashes from the fzf query. Only fzf needs to remove the backslashes
+#     fzfQuery="fzf $fzfParams --query \"${fQuery//\\/}\""
+
+#     # Debugging
+#     if [ -n "$fDebug" ]; then
+#         echo $SEPARATOR_RIGHT
+#         echo -e "rgQuery: ${COLOR}$rgQuery${RESET}"
+#         echo -e "fzfQuery: ${COLOR}$fzfQuery${RESET}"
+#     fi
+
+#     if [ -z "$fQuery" ]; then
+#         fzfSelected=$(eval "$rgQuery" | eval "$fzfQuery")
+#     else
+#         rgResult=$(eval "$rgQuery")
+#         if [ -z "$rgResult" ]; then
+#             echo -e "No result found for query: ${COLOR}$fQuery${RESET}" >&2
+#             exit 1
+#         fi
+#         [ -n "$fOnlyRg" ] && echo "$rgResult" && exit 0
+#         fzfSelected=$(echo "$rgResult" | eval "$fzfQuery")
+#     fi
+
+#     [ -z "$fzfSelected" ] && exit 0
+
+#     # Sample output of fzfResult:
+#     # daemon/wad/wad_app_eng.c:3071:          goto session_make_failed;
+#     # or
+#     # Z15 Bug 0996624 FTP fails active in TP mode/debug2_passive.c:398:CLNT lftp/4.9.2
+#     local filepath lineNumber
+#     pattern='([^:]+):([0-9]+):'
+#     if [[ $fzfSelected =~ $pattern ]]; then
+#         filepath="${BASH_REMATCH[1]}"
+#         linenumber="${BASH_REMATCH[2]}"
+#     else
+#         echo -e "${COLOR}Error: The result is in unexpected format${RESET}"
+#         exit 1
+#     fi
+
+#     # Escape spaces in filepath
+#     filepath="${filepath// /\\ }"
+
+#     if [ -n "$fDebug" ]; then
+#         echo -e "fzf select: ${COLOR}$fzfSelected${RESET}"
+#         echo -e "filepath:   ${COLOR}$filepath${RESET}"
+#         echo -e "linenumber: ${COLOR}$linenumber${RESET}"
+#         echo $SEPARATOR_LEFT
+#     fi
+
+#     if [[ "$fEditor" == "vim" ]]; then
+#         vim +"$lineNumber" "$filepath"
+#     else
+#         "$fEditor" "$filepath:$lineNumber"
+#     fi
+# }
+
 main() {
     parseOptions "$@"
     [ -n "$fCheckDepends" ] && checkDepends
-    [ -z "$fNoClipboard" ]  && GetClipboardContent
+    GetClipboardContent
     polishQuery
     fuzzySearch
 
