add link-clang-format

diff --git a/jc b/jc
--- a/jc
+++ b/jc
@@ -13,7 +13,9 @@ fTKFontConfigDir=$fMainDir/assets/fontconfig
 fTKClangdConfig=$fMainDir/assets/clangd/config.yaml
 fTKtemplateDir=$fMainDir/template
 fTKToolsDir=$fMainDir/ftnt-tools
+fJCPath=$fMainDir/jc
 fUpdateClangd=
+fLinkClangFormatPath=
 fDownloads=$HOME/Downloads
 fHasBeenInvoked=".has_been_invoked"
 # Misc
@@ -28,14 +30,12 @@ fForceUpdate=
 # Constants
 SCRIPT_NAME=$(basename $0)
 # Colors
-CYAN='\033[36m'
 RED='\033[31m'
-BOLD='\033[1m'
 GREEN='\033[32m'
 NORMAL='\033[0m'
 MAGENTA='\033[35m'
-YELLOW='\033[33m'
 LIGHTYELLOW='\033[93m'
+BOLD='\033[1m'
 NORMAL='\033[0m'
 BLUE='\033[34m'
 GREY='\033[90m'
@@ -46,14 +46,15 @@ usage() {
     cat << _EOF
 Usage: $SCRIPT_NAME [OPTIONS]
 
-This script is used to set up the coding environment in my predifined way.
+This script is used to set up the coding environment in my predefined way.
 
 Options:
-    -h, --help          Print this help message
-    -n, --no-tools      Don't install tools
-    -d, --debug         Enable debug mode
-    -u, --update        Force an update of prerequisites
-    --clangd            Update clangd to the latest released version
+    -h, --help              Print this help message
+    -n, --no-tools          Don't install tools
+    -d, --debug             Enable debug mode
+    -u, --update            Force an update of prerequisites
+    --clangd                Update clangd to the latest released version
+    --link-clang-format     Link clang-format to current path
 
 Examples:
     ./$SCRIPT_NAME
@@ -66,7 +67,7 @@ exit 0
 
 parseOptions() {
     SHORTOPTS="hdnu"
-    LONGOPTS="help,debug,no-tools,update,clangd"
+    LONGOPTS="help,debug,no-tools,update,clangd,link-clang-format:"
 
     # Use getopt to parse command-line options
     if ! PARSED=$(getopt --options $SHORTOPTS --longoptions "$LONGOPTS" --name "$0" -- "$@"); then
@@ -90,6 +91,14 @@ parseOptions() {
             --clangd)
                 fUpdateClangd=true
                 shift
+                ;;
+            --link-clang-format)
+                fLinkClangFormatPath="$2"
+                if [ ! -d "$fLinkClangFormatPath" ]; then
+                    echo -e "${LIGHTYELLOW}Link Path $fLinkClangFormatPath does not exist, abort!${RESET}"
+                    exit 1
+                fi
+                shift 2
                 ;;
             -d|--debug)
                 set -x
@@ -562,6 +571,7 @@ createExtraSymlinks() {
     linkFile "$fTKClangdConfig" "$HOME/.config/clangd"
     linkFile "$fzfTabCompPath" "$HOME/.bash_completion.d" "fzf_tab_completion.bash"
     linkFile "$fzfBinPath" "$HOME/.usr/bin"
+    linkFile "$fJCPath" "$HOME/.usr/bin"
 
     echo -e "${COLOR}Relinking system commands${RESET}"
     relinkCommand "batcat" "bat"
@@ -676,9 +686,17 @@ createFirstTimeFile() {
     touch "$fHasBeenInvoked"
 }
 
+linkClangFormat() {
+    local clangFormatPath=$fMainDir/assets/clangd/clang-format
+    echo -e "${LIGHTYELLOW}Linking clang-format to $fLinkClangFormatPath${RESET}"
+    linkFile "$clangFormatPath" "$fLinkClangFormatPath" .clang-format
+    exit 0
+}
+
 main() {
     parseOptions "$@"
     [ ! -f "$fHasBeenInvoked" ] && fForceUpdate=true
+    [ -n "$fLinkClangFormatPath" ] && linkClangFormat
     checkOSCategory
     performSanityCheck
     if [ "$fOSCategory" == "debian" ]; then
